### ISSUE TITLE
Documentation (/doc/auto.tex) is not compiling

### ISSUE THREAD

**Issue by Fr-S** [auto-07p/auto-07p#11]
There seem to be numerous errors, when trying to compile the manual, where the installation instruction should be. These include

1)
- various files in `/doc/include` are in the wrong format, png instead of pdf-
- bibliography is missing

(A complete log of issues and errors that appear when compiling can be found here [auto.log](https://github.com/auto-07p/auto-07p/files/5649028/auto.log))

2)
- some contents in the manual are outdated; e.g. right on the first page of _1.1. Installation_ it says that the current version of `auto`, 0.9.2 can be found `http://cmvl.cs.concordia.ca/auto`, though this link is dead. Perhaps point to this github?

- since Python 3 is not backwards compatible with Python 2, some definitive statement about the Python version in the documentation would be helpful: It would be unusual if both versions of Python would be supported (so if that is indeed that, it would be helpful if this were explicitly mentioned). Currently it is mentioned that "Python 2.7 or higher" is supported, which is slightly ambiguous as to which Python version one should have installed.

I assume that while the software has gone through several updates, the manual has not held pace. It would be great if the manual would be updated too.

**Comment by bartoldeman** [comment]
Quoting the manual:
"
To generate the on-line manual, type \commandf{make} in
\filef{auto/07p/doc}, which depends on the presence of xfig's
(transfig) fig2dev utility.
"
you can't just run pdflatex on the tex file since indeed some figure are first converted. Then for the bibliography bibtex needs to be ran.

The Concordia link still works for me.

Python 3 is definitely supported. The CI (GitHub Actions) tests both 2 and 3.

The manual always can use improvement -- in this case the Python version statement is not incorrect but I agree it could be clarified. Contributions are always welcome (please keep in mind I can only tend to AUTO from time to time as personal development).

**Comment by Fr-S** [comment]
Today the link seems to work; odd.

Regarding the manual, it seems to be a "chicken-egg"-type problem: I'm afraid there is no manual `auto.pdf` in the `doc` folder available, so the instructions you quoted were not available to me, and thus I naturally expected to need to run `pdflatex` on `auto.tex` to obtain the manual in the first place.        
There is also no link to manual under the concordia link (though its existence is mentioned).

If you could fix the readme that says "Please have a look at the manual, `doc/auto.pdf`" to either point to a verified source of the manual, or to mention that the compilation instructions for `auto.tex` actually are inside `auto.tex` themself (on line 276 - should future readers stumble upon this comment) that would be great. Happy to also contribute to the manual.

(BTW, searching the internet brought up this obscure link https://depts.washington.edu/bdecon/workshop2012/auto-tutorial/documentation/auto07p%20manual.pdf though I have not verified if the file indeed is the complete manual.)
