### ISSUE TITLE
Memory error when continuing from a fold continuation point 

### ISSUE THREAD

**Issue by messeli** [auto-07p/auto-07p#15]
I do a fold continuation of a periodic solution branch of a four-state autonomous system. 

However, right at the time the fold continuation is being finalised, the following error is given:
`  free() invalid next size fast()`
However, the fold continuation is itself successful:  I get the results by selecting the data from the terminal prints and plotting elsewhere.

For some values of my parameters, I get the this error, while for some other combination of parameter values I do not get this error and the continuation completes successfully.

How can I solve this? Thanks.

**Comment by messeli** [comment]
I traced the problem back to its root, with the help of `-g` option in `gfortran` compilation, modifying the 07p/src/Makefile, which located the problem to be in the deallocation of `EV` Floquet multipliers vector. With the `WRITE` commands everywhere I noticed the following:

The `free()` error is issued from the deallocation of the `EV` vector under the bvp.f90/`CNRLBV` subroutine.
And the reason of this is the handling and reordering of `EV` in the periodic.f90/`FNSPBV` function after it is calculated in floquet.f90/`FLOWKM` subroutine:
> In periodic.f90/`FNSPBV`, after the `EV` vector comes from `FLOWKM` subroutine, it is first handled to "`! [...] Find the multiplier closest to z=-1.`". 
> Then `EV` is reordered differently than it came. For the fold continuation towards the lower values of my free parameters, the **reordering fails** as it tries to fill the `NDM+1`st dimension of the `EV`. This is caused when the `J+SKIP` quantity exceeds `NDM` for some reason. 

Thus, as a **quick solution**, allocating `NDM+` dimensions to `EV` under bvp.f90/`CNRLBV` solved in my case the issue of `free()` error. Though, a more robust solution is needed.

Points below might suggest that this part of the code with special point continuation (`FNSPBV`) might require a look from the authors: 
> I changed `AZM1= ABS( EV(J) - V )` line in the first handling of `EV` under periodic.f90/`FNSPBV` to `AZM1= ABS( abs(EV(J)) - V )` to mitigate the problem. It pushed the occurrence of the error to lower values of free parameters.
> I changed `EV(J+SKIP)=CMPLX( REAL(ZINS), -AIMAG(ZINS))` to `EV(J+SKIP)=CMPLX( REAL(ZINS), -AIMAG(ZINS), KIND(1.0D0))` for consistency with the precision.

**Comment by bartoldeman** [comment]
Thanks for the report.
From looking at it again, `J+SKIP` can only exceed `NDM` when `SKIP=1` and `J=NDM` which would mean a complex multiplier with positive imaginary part at `EV(NDM)`. But this is impossible from FLOWKM's ordering.

So what must have happened is that in the block before `EV(2)` was swapped with `EV(NDM)`, and `EV(2)` was complex.
For a fold continuation e.g. we could have had with `NDM=4`, `FLOWKM` returning:
1, 1+i, 1-i, 1
the swap to get `EV(2)=1` makes this
1, 1, 1-i, 1+i
and now the assumption is no longer true.

We must therefore be more careful with the swap, and replace it with a shift (i.e. `EV(2)=EV(NDM)` after shifting `EV(2...NDM-1)` to `EV(3...NDM)` to keep the ordering intact, also this only makes sense if `EV(NDM)` is real.

I'll do another commit to properly fix this.

as for the "points below",
`AZM1= ABS( abs(EV(J)) - V )` is not correct; as on PD curves `EV(J)` should be close to `-1` and `V=-1`.
the consistency fix for precision was already fixed in git.
